import type { FilterGroup, MarketAsset } from "@/types/market";

export const marketAssets: MarketAsset[] = [
  {
    symbol: "NVDA",
    name: "NVIDIA",
    type: "stock",
    sector: "Technology",
    price: 124.8,
    changePercent: 8.4,
    volume: 138_000_000,
    ma52: 116.4,
    trendScore: 91,
    lookback3m: 24.1,
    lookback5m: 7.6,
    recoveryCount: 3,
    followers: 128_000,
    likeCount: 840,
    dislikeCount: 73,
    notes: "Momentum remains strong with breakout volume.",
  },
  {
    symbol: "AMD",
    name: "Advanced Micro Devices",
    type: "stock",
    sector: "Technology",
    price: 175.2,
    changePercent: -6.8,
    volume: 96_000_000,
    ma52: 164.7,
    trendScore: 74,
    lookback3m: 18.9,
    lookback5m: -4.7,
    recoveryCount: 2,
    followers: 94_000,
    likeCount: 530,
    dislikeCount: 61,
    notes: "Still above its 52-day average after a sharp pullback.",
  },
  {
    symbol: "BTC",
    name: "Bitcoin",
    type: "crypto",
    sector: "Digital Assets",
    price: 67840,
    changePercent: 11.2,
    volume: 38_000_000_000,
    ma52: 62120,
    trendScore: 88,
    lookback3m: 22.4,
    lookback5m: 9.6,
    recoveryCount: 4,
    followers: 312_000,
    likeCount: 1040,
    dislikeCount: 128,
    notes: "High-volume breakout after a volatile rebound.",
  },
  {
    symbol: "GLD",
    name: "Gold ETF",
    type: "commodity",
    sector: "Precious Metals",
    price: 231.5,
    changePercent: -5.1,
    volume: 22_400_000,
    ma52: 223.1,
    trendScore: 69,
    lookback3m: 16.7,
    lookback5m: -6.2,
    recoveryCount: 2,
    followers: 67_000,
    likeCount: 320,
    dislikeCount: 47,
    notes: "A defensive move that remains above its 52-day average.",
  },
  {
    symbol: "TLT",
    name: "iShares 20+ Year Treasury",
    type: "treasury",
    sector: "Rates",
    price: 95.3,
    changePercent: 5.8,
    volume: 12_100_000,
    ma52: 90.1,
    trendScore: 80,
    lookback3m: 13.4,
    lookback5m: 6.3,
    recoveryCount: 3,
    followers: 48_000,
    likeCount: 199,
    dislikeCount: 29,
    notes: "Price action is showing a strong rate-sensitive rebound.",
  },
];

export function buildFilterGroups(assets: MarketAsset[] = marketAssets): FilterGroup[] {
  return [
    {
      id: "recovery-candidates",
      title: "Recovery candidates",
      description: "Assets that have recovered 15-20%+ multiple times and are currently re-testing support.",
      assets: assets.filter((asset) => asset.recoveryCount >= 2 && asset.changePercent < 0),
    },
    {
      id: "movers",
      title: "5-10% movers",
      description: "Assets showing meaningful short-term movement while remaining above the 52-day average.",
      assets: assets.filter((asset) => Math.abs(asset.lookback5m) >= 5 && asset.price > asset.ma52),
    },
    {
      id: "gainers",
      title: "20%+ gainers",
      description: "Assets with strong 3-month momentum for trend followers.",
      assets: assets.filter((asset) => asset.lookback3m >= 20),
    },
    {
      id: "high-volume",
      title: "High-volume setups",
      description: "Assets experiencing unusually strong participation.",
      assets: assets.filter((asset) => asset.volume > 20_000_000),
    },
  ];
}
